### ISSUE TITLE
Switch Largo initialization to `release` branch

### ISSUE THREAD

**Issue by joshdarby** [INN/umbrella-boilerplate#6]
https://github.com/INN/umbrella-boilerplate/blob/178c39e220ff58d6d54390871a0a9caf563aa5bb/initialize.sh#L25-L28

We should switch to the `release` branch of Largo instead of `master`. Currently `master` sits behind `release`, so as it stands, any time we use this boilerplate we have to check out the most recent release of Largo in whatever project we're working on with this boilerplate.

**Comment by benlk** [comment]
`master` isn't even part of the working Largo tree; we might have been using the `trunk` branch here.
```diff
-git submodule add -f https://github.com/INN/largo.git wp-content/themes/largo
+git submodule add -b release -f https://github.com/INN/largo.git wp-content/themes/largo
```
